version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:17"
      timezone: America/Montreal
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:27"
      timezone: America/Montreal
    open-pull-requests-limit: 3
    groups:
      documentation:
        patterns:
          - "*"
    commit-message:
      prefix: build(docs)
