enable_obituary = true
replaceable_blocks = ["#gravestone:grave_replaceable"]
remove_obituary = true
only_owners_can_break = true
spawn_ghost = false
friendly_ghost = true
sneak_pickup = false
break_pickup = true
strict_placement = false
