#!/usr/bin/env python3
"""Generate factual pack reference documentation from tracked sources."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).parents[1]
OUTPUT = ROOT / "docs/reference/pack.md"


def project_id(entry: dict) -> str:
    parts = urlparse(entry["downloads"][0]).path.split("/")
    if len(parts) < 4 or parts[1] != "data":
        raise ValueError(f"unexpected Modrinth URL: {entry['downloads'][0]}")
    return parts[2]


def environment_counts(entries: list[dict], side: str) -> Counter:
    return Counter(entry.get("env", {}).get(side, "unspecified") for entry in entries)


def recipe_locks(root: Path) -> list[Path]:
    data_root = root / "overrides/config/universaldatapack/data"
    locks = []
    for path in data_root.rglob("*.json"):
        if json.loads(path.read_text()) == {}:
            locks.append(path.relative_to(data_root))
    return sorted(locks)


def config_files(root: Path) -> list[Path]:
    config_root = root / "overrides/config"
    data_root = config_root / "universaldatapack/data"
    return sorted(
        path.relative_to(root / "overrides")
        for path in config_root.rglob("*")
        if path.is_file() and not path.is_relative_to(data_root)
    )


def quest_summary(root: Path) -> tuple[list[tuple[str, int]], int]:
    quest_root = root / "overrides/config/simplyquests"
    groups = json.loads((quest_root / "groups.json").read_text())
    chapter_order = groups["groups"][0]["chapters"]
    chapters = {}
    for path in (quest_root / "chapters").glob("*.json"):
        chapter = json.loads(path.read_text())
        chapters[chapter["name"]] = chapter
    summary = [(chapters[name]["title"], len(chapters[name]["quests"])) for name in chapter_order]
    return summary, sum(count for _, count in summary)


def render(root: Path = ROOT) -> str:
    manifest = json.loads((root / "modrinth.index.json").read_text())
    entries = manifest["files"]
    dependencies = manifest["dependencies"]
    client_counts = environment_counts(entries, "client")
    server_counts = environment_counts(entries, "server")
    locks = recipe_locks(root)
    configs = config_files(root)
    chapters, quest_count = quest_summary(root)

    lines = [
        "# Generated pack reference",
        "",
        "<!-- Generated by scripts/generate_reference.py; do not edit by hand. -->",
        "",
        "This page is derived from the tracked Modrinth manifest and pack overrides.",
        "Run `scripts/generate_reference.py` after changing those sources.",
        "",
        "## Baseline",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Pack | {manifest['name']} {manifest['versionId']} |",
        f"| Minecraft | {dependencies['minecraft']} |",
        f"| NeoForge | {dependencies['neoforge']} |",
        f"| Artifacts | {len(entries)} |",
        f"| Client required | {client_counts['required']} |",
        f"| Client optional | {client_counts['optional']} |",
        f"| Client unsupported | {client_counts['unsupported']} |",
        f"| Server required | {server_counts['required']} |",
        f"| Server optional | {server_counts['optional']} |",
        f"| Server unsupported | {server_counts['unsupported']} |",
        f"| Recipe locks | {len(locks)} |",
        f"| Quest chapters | {len(chapters)} |",
        f"| Quest milestones | {quest_count} |",
        "",
        "## Artifacts",
        "",
        "| Artifact | Project | Client | Server |",
        "| --- | --- | --- | --- |",
    ]
    for entry in sorted(entries, key=lambda item: item["path"].casefold()):
        identifier = project_id(entry)
        filename = Path(entry["path"]).name
        client = entry.get("env", {}).get("client", "unspecified")
        server = entry.get("env", {}).get("server", "unspecified")
        lines.append(
            f"| `{filename}` | [Modrinth](https://modrinth.com/project/{identifier}) "
            f"| {client} | {server} |"
        )

    lines.extend([
        "",
        "## Recipe locks",
        "",
        "Empty datapack recipes remove these survival crafting paths:",
        "",
    ])
    lines.extend(f"- `{path.as_posix()}`" for path in locks)

    lines.extend([
        "",
        "## Shipped configuration and assets",
        "",
    ])
    lines.extend(f"- `{path.as_posix()}`" for path in configs)

    lines.extend([
        "",
        "## Quest notebook",
        "",
        "| Chapter | Milestones |",
        "| --- | ---: |",
    ])
    lines.extend(f"| {title} | {count} |" for title, count in chapters)
    lines.extend(["", f"Total: **{quest_count} milestones**.", ""])
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print(f"Generated reference is stale: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            print("Run scripts/generate_reference.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected)
    print(OUTPUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
